<?php
/*
 * File generated by ModulesGarden packages system
 * 
 * Below you can find current version & revision of this module
 */

$moduleVersion = '3.10.0';
$moduleRevision = 'd522e0be0912e1be580004134dc36095a5adeedc';
$moduleWikiUrl = 'http://www.docs.modulesgarden.com/Proxmox_VPS_For_WHMCS';